spring:
  profiles:
    active: local

  application:
    name: APIRateLimiter

  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      database: ${DATABASE_NAME}
      auto-index-creation: true


limit:
  allowed:
    apiLimit: ${ALLOWED_API_LIMIT}
    databaseLimit: ${ALLOWED_DATABASE_LIMIT}
    anonymousLimit: ${ALLOWED_ANONYMOUS_LIMIT}


token:
  exp:
    accessToken: ${ACCESS_EXP_TIME}
    refreshToken: ${REFRESH_EXP_TIME}

jwt:
  secret: ${JWT_SECRET}


message:
  access:
    api: ${API_ACCESS_EXCEEDED_MSG}
    database: ${DATABASE_ACCESS_EXCEEDED_MSG}
    anonymous: ${ANONYMOUS_ACCESS_EXCEEDED_MSG}

